title: Personal Blog
description: A personal knowledge base

baseurl: "/Personal_Blog"
url: "https://BeardedOwl1357.github.io"

collections:
  articles:
    output: true

  domains:
    output: true

defaults:
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "default"

  - scope:
      path: ""
      type: "domains"
    values:
      layout: "domain"

markdown: kramdown

kramdown:
  input: GFM

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock