title: Personal Notes
description: A personal knowledge base
baseurl: "/Personal_Blog"
url: "https://BeardedOwl1357.github.io"

collections:
  articles:
    output: true

defaults:
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "default"

markdown: kramdown
kramdown:
  input: GFM

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
